import { WeeklyMenu } from './types'

export const DEFAULT_MENU: WeeklyMenu = {
  items: [
    {
      hari: 'Senin',
      pagi: ['Nasi Uduk Gurih', 'Semur Telur & Tahu', 'Bihun Goreng', 'Sambal Kacang', 'Kerupuk'],
      siang: ['Nasi', 'Ayam Serundeng', 'Lalap Sayur', 'Tempe Crispy', 'Kerupuk'],
      malam: ['Nasi', 'Ayam Kremes', 'Lalap', 'Kerupuk'],
    },
    {
      hari: 'Selasa',
      pagi: ['Lontong Sayur Labu Siam', 'Telur Balado', 'Tahu Goreng', 'Bawang Goreng', 'Kerupuk'],
      siang: ['Nasi', 'Chicken Blackpepper', 'Salad Sayur', 'French Fries'],
      malam: ['Nasi', 'Chicken Pop', 'Sambal Matah', 'Timun', 'Kerupuk'],
    },
    {
      hari: 'Rabu',
      pagi: ['Bubur Ayam Komplit', 'Cakwe Crispy', 'Ayam Suwir Gurih', 'Kuah Kaldu Kuning', 'Emping'],
      siang: ['Nasi', 'Ikan Cabe Ijo', 'Cah Tauge', 'Kerupuk'],
      malam: ['Nasi', 'Ikan Balado Kentang', 'Sayur Sawi Putih', 'Kerupuk'],
    },
    {
      hari: 'Kamis',
      pagi: ['Nasi Kuning Harum', 'Ayam Goreng Lengkuas', 'Orek Tempe Manis', 'Telur Dadar Iris', 'Sambal'],
      siang: ['Nasi', 'Ayam Gulai Korma', 'Rebusan Sayur', 'Sambal Tomat', 'Kerupuk'],
      malam: ['Nasi', 'Ayam Cabe Ijo Kentang', 'Sayur Bayam', 'Kerupuk'],
    },
    {
      hari: 'Jumat',
      pagi: ['Nasi Liwet Teri Medan', 'Telur Pindang', 'Tahu Bacem', 'Sambal Terasi', 'Kerupuk'],
      siang: ['Nasi', 'Daging Kentang Balado', 'Sayur Sawi Putih', 'Kerupuk'],
      malam: ['Nasi', 'Soto Padang'],
    },
    {
      hari: 'Sabtu',
      pagi: ['Roti Bakar Dapoer Iboe', 'Omelette Sayur Keju', 'Sosis Panggang', 'Salad Buah Segar'],
      siang: ['Nasi', 'Ayam Daun Jeruk', 'Cah Buncis', 'Tempe', 'Kerupuk'],
      malam: ['Nasi', 'Ayam Kecap Tahu', 'Bihun Goreng', 'Kerupuk', 'Buah'],
    },
  ],
  updatedAt: new Date().toISOString(),
}

export const DEFAULT_PELANGGAN = [
  {
    id: 'pelanggan-1',
    nama: 'Budi Santoso',
    whatsapp: '081234567890',
    alamat: 'Jl. Merdeka No. 12, Jakarta Selatan (Rumah Pagar Hitam)',
    jadwal: 'semua' as const,
    mulaiTanggal: '2026-08-01',
    catatan: 'Jangan terlalu pedas, sayur dipisah',
    status: 'aktif' as const,
    createdAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'pelanggan-2',
    nama: 'Siti Rahmawati',
    whatsapp: '085678901234',
    alamat: 'Apartemen Sudirman Tower A Lt. 15 No. 08, Jakpus',
    jadwal: 'pagi' as const,
    mulaiTanggal: '2026-08-10',
    catatan: 'Titip ke resepsionis/lobby jika belum bangun',
    status: 'aktif' as const,
    createdAt: '2026-08-10T09:30:00.000Z',
  },
  {
    id: 'pelanggan-3',
    nama: 'Ahmad Fauzi',
    whatsapp: '081398765432',
    alamat: 'Komplek Permata Hijau Blok C3/15, Kebayoran Lama',
    jadwal: 'malam' as const,
    mulaiTanggal: '2026-08-15',
    catatan: 'Alergi seafood/udang',
    status: 'aktif' as const,
    createdAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'pelanggan-4',
    nama: 'Dewi Lestari',
    whatsapp: '087811223344',
    alamat: 'Jl. Tebet Barat Dalam Raya No. 45, Jakarta Selatan',
    jadwal: 'siang' as const,
    mulaiTanggal: '2026-08-25',
    catatan: 'Porsi nasi sedikit saja',
    status: 'pending' as const,
    createdAt: '2026-08-25T07:15:00.000Z',
  },
  {
    id: 'pelanggan-5',
    nama: 'Rian Pratama',
    whatsapp: '089944556677',
    alamat: 'Gedung Wisma GKBI Lt. 20, Jl. Jend Sudirman Kav. 28',
    jadwal: 'keduanya' as const,
    mulaiTanggal: '2026-08-26',
    catatan: 'Mohon antar tepat jam 11:30 siang & jam 18:00 malam',
    status: 'pending' as const,
    createdAt: '2026-08-25T13:45:00.000Z',
  },
  {
    id: 'pelanggan-6',
    nama: 'Hendra Gunawan',
    whatsapp: '082155667788',
    alamat: 'Jl. Kemang Raya No. 88B, Jakarta Selatan',
    jadwal: 'malam' as const,
    mulaiTanggal: '2026-07-15',
    catatan: 'Sedang libur dinas luar kota',
    status: 'nonaktif' as const,
    createdAt: '2026-07-15T10:00:00.000Z',
  },
]
